clusters:
  - name: grupo-cluster

    bootstrap_servers:
     - localhost:9094

    security:
      protocol: SSL

      ssl:
        ca_location: "../config/certs/CARoot.pem"
        certificate_location: "../config/certs/certificate.pem"
        key_location: "../config/certs/key.pem"
        endpoint_identification_algorithm: "none"

    monitoring:
      inactivity_hours: 6
      low_volume_threshold: 100

    storage:
      sqlite_path: storage/msk_monitor.db